(function(){
  "use strict";
  const F=window.MED_FIXTURES;
  const KEY="med-assurance-demo-v1";
  const freshState=()=>({claimStep:1,draft:null,submitted:null,selectedClient:F.clients[0].id,approvedDrafts:[],imports:[],importedRecords:[],clientUpdates:{}});
  let state=load();
  let importTimer=null;
  const $=(s,r=document)=>r.querySelector(s);
  const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=(v)=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  function load(){try{const loaded=JSON.parse(localStorage.getItem(KEY)||"{}");return {...freshState(),...loaded,approvedDrafts:Array.isArray(loaded.approvedDrafts)?loaded.approvedDrafts:[],imports:Array.isArray(loaded.imports)?loaded.imports:[],importedRecords:Array.isArray(loaded.importedRecords)?loaded.importedRecords:[],clientUpdates:loaded.clientUpdates&&typeof loaded.clientUpdates==="object"?loaded.clientUpdates:{}}}catch{return freshState()}}
  function save(){localStorage.setItem(KEY,JSON.stringify(state))}
  function toast(text){$("#toast").textContent=text;$("#toast").classList.add("show");$("#live").textContent=text;setTimeout(()=>$("#toast").classList.remove("show"),2600)}
  function route(name){
    const valid=$(`[data-view="${CSS.escape(name)}"]`)?name:"dashboard";
    $$("[data-view]").forEach(v=>v.hidden=v.dataset.view!==valid);
    $$("[data-route]").forEach(a=>a.classList.toggle("active",a.dataset.route===valid));
    document.title=`${valid==="dashboard"?"Med Assurance":$("[data-view="+valid+"] h1")?.textContent||"Med Assurance"} · Démo`;
    window.scrollTo(0,0);
    $("#main").focus({preventScroll:true});
  }
  window.addEventListener("hashchange",()=>route(location.hash.slice(1)));
  $$('[data-route]').forEach(a=>a.addEventListener("click",()=>route(a.dataset.route)));
  $$('[data-go]').forEach(b=>b.addEventListener("click",()=>{location.hash=b.dataset.go}));

  function submittedClaim(){if(!state.submitted)return null;const u=state.clientUpdates[`CLIENT-${state.submitted.id}`];return {id:state.submitted.id,client:state.submitted.claimant||"Conducteur démo",title:`${state.submitted.type} · ${state.submitted.city}`,status:u?.status||"Reçu dans la démo",tone:"violet",date:"Aujourd'hui",source:"Formulaire local"}}
  function allClaims(){const submitted=submittedClaim();return submitted?[submitted,...F.claims]:[...F.claims]}
  function allClients(){const records=state.importedRecords.map(r=>({id:r.id,name:r.name,phone:"Non renseigné",city:r.city,policy:r.policy,vehicle:r.vehicle,source:r.source,fresh:r.fresh,owner:"À attribuer",history:[`${r.fresh} · Import accepté localement`],tasks:["Vérifier les champs importés"]}));if(state.submitted)records.unshift({id:`CLIENT-${state.submitted.id}`,name:state.submitted.claimant,phone:"Non renseigné",city:state.submitted.city,policy:state.submitted.policy||"Non renseignée",vehicle:"À renseigner",source:"Déclaration locale",fresh:"Aujourd'hui",owner:"À attribuer",history:[`Aujourd'hui · ${state.submitted.type} déclaré`,"Aujourd'hui · Reçu dans la file broker"],tasks:["Relire la déclaration","Confirmer la prochaine étape au client"]});return [...records,...F.clients]}
  function renderClaims(){
    const claims=allClaims();
    $("#open-count").textContent=claims.length;
    $("#claim-cards").innerHTML=claims.map(c=>`<div class="claim-card"><div><strong>${esc(c.title)}</strong><small>${esc(c.id)} · ${esc(c.client)} · ${esc(c.date)}</small></div><span class="status ${esc(c.tone)}">${esc(c.status)}</span></div>`).join("");
    const tasks=F.clients.flatMap(c=>c.tasks.map(t=>({client:c.name,text:t}))).slice(0,4);
    $("#task-list").innerHTML=tasks.map(t=>`<div class="task"><strong>${esc(t.text)}</strong><small>${esc(t.client)}</small></div>`).join("");
    $("#task-count").textContent=tasks.length;
    $("#ai-claim").innerHTML=claims.map(c=>`<option value="${esc(c.id)}">${esc(c.id)} · ${esc(c.client)}</option>`).join("");
  }

  const form=$("#claim-form");
  function setStep(n){state.claimStep=Math.max(1,Math.min(4,n));state.draft=formData();save();$$('[data-step]',form).forEach(f=>f.hidden=Number(f.dataset.step)!==state.claimStep);$$('.stepper li').forEach((li,i)=>li.classList.toggle("active",i<state.claimStep));$("#claim-step-badge").textContent=`Étape ${state.claimStep} / 4`;$("#back").hidden=state.claimStep===1;$("#next").hidden=state.claimStep===4;$("#submit-claim").hidden=state.claimStep!==4;if(state.claimStep===4)renderReview()}
  function formData(){const d=Object.fromEntries(new FormData(form));d.documents=$$('.doc-row').map(r=>({name:$('.doc-name',r).value,type:$('.doc-type',r).value})).filter(x=>x.name);return d}
  function validStep(){const field=$(`[data-step="${state.claimStep}"]`,form);const invalid=$$("input,select,textarea",field).find(x=>!x.checkValidity());if(invalid){invalid.reportValidity();return false}return true}
  function validateAll(){const invalid=$$("input[required],select[required],textarea[required]",form).find(x=>!x.checkValidity());if(!invalid)return true;const field=invalid.closest('[data-step]');if(field)setStep(Number(field.dataset.step));invalid.reportValidity();return false}
  function addDoc(name="",type="Photo du véhicule"){$("#doc-rows").insertAdjacentHTML("beforeend",`<div class="doc-row"><label>Nom du fichier<input class="doc-name" value="${esc(name)}" placeholder="photo-avant.jpg"></label><label>Type<select class="doc-type"><option ${type==="Photo du véhicule"?"selected":""}>Photo du véhicule</option><option ${type==="Constat"?"selected":""}>Constat</option><option ${type==="Procès-verbal"?"selected":""}>Procès-verbal</option><option ${type==="Autre"?"selected":""}>Autre</option></select></label><button type="button" class="ghost remove-doc" aria-label="Supprimer ce document">Supprimer</button></div>`)}
  function restoreDraft(){if(!state.draft)return;for(const [k,v] of Object.entries(state.draft)){const control=form.elements[k];if(!control||k==="documents")continue;if(control instanceof RadioNodeList){const item=$(`input[name="${k}"][value="${CSS.escape(v)}"]`,form);if(item)item.checked=true}else control.value=v}if(state.draft.documents?.length){$("#doc-rows").innerHTML="";for(const d of state.draft.documents)addDoc(d.name,d.type)}updateInjury()}
  function renderReview(){const d=formData();$("#review").innerHTML=`<div class="profile-grid"><div><small>Sécurité</small><strong>${esc(d.injury||"Non répondu")}</strong></div><div><small>Type</small><strong>${esc(d.type||"Non renseigné")}</strong></div><div><small>Lieu</small><strong>${esc(d.city||"Non renseigné")}</strong></div></div><p><strong>Description</strong><br>${esc(d.description||"Non renseignée")}</p><p><strong>Documents</strong><br>${d.documents.length?d.documents.map(x=>`${esc(x.name)} (${esc(x.type)})`).join("<br>"):"Aucun"}</p>`}
  function updateInjury(){const val=form.elements.injury.value;$("#injury-alert").hidden=val!=="yes"&&val!=="unknown"}
  function persistDraft(){state.draft=formData();save()}
  form.addEventListener("input",persistDraft);form.addEventListener("change",e=>{if(e.target.name==="injury")updateInjury();persistDraft()});
  $("#next").addEventListener("click",()=>{if(validStep())setStep(state.claimStep+1)});$("#back").addEventListener("click",()=>setStep(state.claimStep-1));
  $("#add-doc").addEventListener("click",()=>addDoc());$("#doc-rows").addEventListener("click",e=>{if(e.target.matches('.remove-doc'))e.target.closest('.doc-row').remove()});
  $("#save-draft").addEventListener("click",()=>{state.draft=formData();save();toast("Brouillon enregistré dans ce navigateur.")});
  function renderTracking(){if(!state.submitted)return;const u=state.clientUpdates[`CLIENT-${state.submitted.id}`];$("#tracking").hidden=false;$("#tracking").innerHTML=`<h2>${esc(state.submitted.id)} · ${esc(u?.status||"Reçu dans la démo")}</h2><div class="timeline"><p><strong>Enregistré localement</strong><br>Déclaration ajoutée au suivi et à la file broker</p>${(u?.timeline||[]).map(x=>`<p>${esc(x)}</p>`).join("")}<p><strong>Étape suivante</strong><br>Revue par un broker humain</p><p><strong>Non effectué</strong><br>Aucun envoi externe, aucune décision de garantie</p></div>`}
  form.addEventListener("submit",e=>{e.preventDefault();if(!validateAll())return;if(!$("#accuracy").checked){toast("Confirmez la vérification avant l'envoi simulé.");return}const d=formData();state.submitted={...d,id:state.submitted?.id||`SIN-DEMO-${String(Date.now()).slice(-5)}`};state.selectedClient=`CLIENT-${state.submitted.id}`;state.draft=null;save();renderClaims();renderTracking();renderClients();toast("Déclaration ajoutée au suivi local et à la file broker.")});

  function renderClients(filter=""){
    const q=filter.trim().toLocaleLowerCase("fr");const clients=allClients();const list=clients.filter(c=>[c.name,c.policy,c.city].join(" ").toLocaleLowerCase("fr").includes(q));
    $("#client-list").innerHTML=list.length?list.map(c=>`<button type="button" class="client-button ${c.id===state.selectedClient?"active":""}" data-client="${c.id}"><strong>${esc(c.name)}</strong><small>${esc(c.policy)} · ${esc(c.city)}</small></button>`).join(""):`<p class="empty">Aucun client fictif trouvé.</p>`;
    const client=clients.find(c=>c.id===state.selectedClient)||list[0];if(client){state.selectedClient=client.id;renderProfile(client)}else $("#client-profile").innerHTML='<p class="empty">Aucun profil à afficher.</p>';
  }
  function renderProfile(c){const u=state.clientUpdates[c.id]||{status:"À qualifier",tasks:[],timeline:[]};const statuses=["À qualifier","En revue","En attente client","Escalade humaine","Clos"];$("#client-profile").innerHTML=`<div class="panel-head"><div><p class="eyebrow">${esc(c.id)}</p><h2>${esc(c.name)}</h2></div><span class="badge">${esc(c.owner)}</span></div><div class="profile-grid"><div><small>Police</small><strong>${esc(c.policy)}</strong></div><div><small>Véhicule</small><strong>${esc(c.vehicle)}</strong></div><div><small>Contact masqué</small><strong>${esc(c.phone)}</strong></div><div><small>Source</small><strong>${esc(c.source)}</strong></div><div><small>Fraîcheur</small><strong>${esc(c.fresh)}</strong></div><div><small>Ville</small><strong>${esc(c.city)}</strong></div></div><h3>Historique</h3><div class="timeline">${[...c.history,...u.timeline].map(h=>`<p>${esc(h)}</p>`).join("")}</div><h3>Tâches</h3>${c.tasks.map((t,i)=>`<div class="task"><label class="choice"><input type="checkbox" data-task="${i}" ${u.tasks.includes(i)?"checked":""}> ${esc(t)}</label></div>`).join("")}<label>Statut du dossier<select data-client-status>${statuses.map(s=>`<option ${u.status===s?"selected":""}>${s}</option>`).join("")}</select></label>`}
  $("#client-search").addEventListener("input",e=>renderClients(e.target.value));$("#client-list").addEventListener("click",e=>{const b=e.target.closest('[data-client]');if(!b)return;state.selectedClient=b.dataset.client;save();renderClients($("#client-search").value)});
  $("#client-profile").addEventListener("change",e=>{const c=allClients().find(x=>x.id===state.selectedClient);if(!c)return;const u=state.clientUpdates[c.id]||{status:"À qualifier",tasks:[],timeline:[]};if(e.target.matches('[data-task]')){const index=Number(e.target.dataset.task);u.tasks=e.target.checked?[...new Set([...u.tasks,index])]:u.tasks.filter(x=>x!==index);u.timeline.push(`${new Date().toLocaleDateString("fr-MA")} · Tâche ${e.target.checked?"terminée":"réouverte"}: ${c.tasks[index]}`)}if(e.target.matches('[data-client-status]')){u.status=e.target.value;u.timeline.push(`${new Date().toLocaleDateString("fr-MA")} · Statut local: ${u.status}`)}state.clientUpdates[c.id]=u;save();renderProfile(c);renderClaims();renderTracking();toast("Profil mis à jour localement.")});

  $("#generate").addEventListener("click",()=>{const claim=allClaims().find(c=>c.id===$("#ai-claim").value);if(!claim)return toast("Le sinistre sélectionné n'est plus disponible.");const purpose=$("#ai-purpose").value;$("#ai-draft").value=`Bonjour ${claim.client},\n\nNous avons bien enregistré votre dossier ${claim.id}. Objet: ${purpose.toLowerCase()}. Un membre de notre équipe vérifiera les informations et vous indiquera la prochaine étape. Cette confirmation ne constitue pas une décision de garantie, de responsabilité ou d'indemnisation.\n\nCordialement,\nL'équipe Med Assurance (démo)`;$("#ai-sources").innerHTML=`<strong>Sources du brouillon</strong><br>${esc(claim.id)} · fixture locale<br>Guide ACAPS dégâts matériels · principe de revue par l'assureur<br><em>Le texte reste à valider par un broker humain.</em>`;$("#human-approved").checked=false;$("#approve-draft").disabled=true;toast("Brouillon déterministe généré localement.")});
  $("#human-approved").addEventListener("change",e=>$("#approve-draft").disabled=!e.target.checked);$("#approve-draft").addEventListener("click",()=>{if(!$("#ai-draft").value.trim())return toast("Générez ou saisissez un brouillon d'abord.");state.approvedDrafts.push({claim:$("#ai-claim").value,at:new Date().toISOString()});save();toast("Brouillon approuvé localement. Aucun message envoyé.")});

  const importFixtures={new:[{field:"Police",current:"Non renseigné",incoming:"MA-AUTO-25001",status:"Nouveau"},{field:"Véhicule",current:"Non renseigné",incoming:"Citroën C3 · 2022",status:"Nouveau"}],duplicate:[{field:"Police",current:"MA-AUTO-24018",incoming:"MA-AUTO-24018",status:"Doublon"},{field:"Client",current:"Nadia El Mansouri",incoming:"Nadia El Mansouri",status:"Doublon"}],conflict:[{field:"Téléphone",current:"06•••••142",incoming:"06•••••913",status:"Conflit"},{field:"Véhicule",current:"Dacia Sandero · 2022",incoming:"Dacia Sandero · 2021",status:"Conflit"}]};
  function endImport(kind,source){if(kind==="failure"){$("#import-status").innerHTML=`<div class="activity"><span class="dot bad"></span><strong>Interrompu</strong></div><p>Structure de page inconnue. Aucun champ accepté; reprise manuelle requise.</p>`;return}const rows=importFixtures[kind];$("#import-status").innerHTML=`<div class="activity"><span class="dot ok"></span><strong>Lecture simulée terminée</strong></div><p>Source: ${esc(source)}<br>Horodatage: ${esc(new Date().toISOString())}<br>Mode: fixture locale, aucune connexion</p>`;$("#mapping").hidden=false;$("#mapping-status").textContent=kind==="conflict"?"CONFLIT À RÉSOUDRE":kind==="duplicate"?"DOUBLON DÉTECTÉ":"PRÊT À RELIRE";$("#mapping-table").innerHTML=`<div class="mapping-row"><strong>Champ</strong><strong>CRM actuel</strong><strong>Valeur lue</strong></div>`+rows.map(r=>`<div class="mapping-row ${r.status==="Conflit"?"conflict":""}"><span>${esc(r.field)}<small>${esc(r.status)}</small></span><span>${esc(r.current)}</span><span>${esc(r.incoming)}</span></div>`).join("");$("#accept-import").disabled=kind!=="new";$("#accept-import").dataset.kind=kind}
  $("#run-import").addEventListener("click",()=>{clearTimeout(importTimer);const kind=$("#import-case").value,source=$("#import-source").value;$("#mapping").hidden=true;$("#import-status").innerHTML=`<div class="activity"><span class="dot"></span><strong>Lecture simulée en cours…</strong></div><p>Ouverture → authentification autorisée → extraction visible → mapping</p>`;importTimer=setTimeout(()=>endImport(kind,source),700)});$("#cancel-import").addEventListener("click",()=>{clearTimeout(importTimer);importTimer=null;$("#mapping").hidden=true;$("#import-status").textContent="Simulation annulée. Aucune donnée acceptée.";toast("Import annulé.")});$("#accept-import").addEventListener("click",e=>{if(e.target.dataset.kind!=="new")return;const existing=allClients().find(c=>c.policy==="MA-AUTO-25001");if(existing){e.target.disabled=true;$("#mapping-status").textContent="DÉJÀ IMPORTÉ";return toast("Police déjà présente: aucun doublon créé.")}const source=$("#import-source").value,at=new Date().toISOString();const record={id:`IMPORT-${String(Date.now()).slice(-5)}`,name:"Client importé (démo)",policy:"MA-AUTO-25001",vehicle:"Citroën C3 · 2022",city:"Non renseignée",source:`${source} · simulation locale`,fresh:at};state.imports.push({kind:"new",at,recordId:record.id});state.importedRecords.push(record);state.selectedClient=record.id;save();renderClients();e.target.disabled=true;$("#mapping-status").textContent="AJOUTÉ AU CRM LOCAL";toast("Enregistrement ajouté au CRM local avec sa provenance.")});

  function renderDirectory(){$("#directory-cards").innerHTML=F.directory.map(d=>`<article class="glass directory-card"><p class="eyebrow">${esc(d.role)}</p><h2>${esc(d.name)}</h2><p class="phone">${esc(d.phone)}</p><p>${esc(d.note)}</p><a href="${esc(d.url)}" target="_blank" rel="noopener noreferrer">Ouvrir la source officielle ↗</a></article>`).join("")}
  $("#reset").addEventListener("click",()=>{if(!confirm("Effacer le brouillon et toutes les actions locales de la démo?"))return;clearTimeout(importTimer);importTimer=null;localStorage.removeItem(KEY);state=freshState();form.reset();$("#doc-rows").innerHTML="";addDoc();$("#tracking").hidden=true;$("#ai-draft").value="";$("#ai-sources").textContent="";$("#human-approved").checked=false;$("#approve-draft").disabled=true;$("#mapping").hidden=true;$("#mapping-table").textContent="";$("#mapping-status").textContent="";$("#import-status").textContent="Aucune simulation lancée.";$("#client-search").value="";updateInjury();setStep(1);renderClaims();renderClients();toast("Démo réinitialisée.")});

  if(!$("#doc-rows").children.length)addDoc();restoreDraft();setStep(state.claimStep);renderClaims();renderTracking();renderClients();renderDirectory();route(location.hash.slice(1)||"dashboard");
})();
