import assert from "node:assert/strict";
import {readFileSync, readdirSync} from "node:fs";
import {join} from "node:path";
const root=new URL("..",import.meta.url).pathname.replace(/\/$/,"");
const files=["index.html","styles.css","data.js","app.js","README.md","CHALLENGE.md","BONUS.md","SOURCES.md","server.py","package.json"];
for(const file of files)assert.ok(readFileSync(join(root,file),"utf8").length>20,`${file} missing or empty`);
const html=readFileSync(join(root,"index.html"),"utf8");
const js=readFileSync(join(root,"app.js"),"utf8");
const data=readFileSync(join(root,"data.js"),"utf8");
for(const view of ["dashboard","claim","crm","ai","imports","directory"])assert.match(html,new RegExp(`data-view="${view}"`));
for(const behavior of ["localStorage","human-approved","run-import","injury-alert","client-search"])assert.ok(html.includes(behavior)||js.includes(behavior),`missing ${behavior}`);
for(const forbidden of [/fetch\s*\(/,/XMLHttpRequest/,/WebSocket\s*\(/,/https?:\/\/[^"']+\.js/])assert.ok(!forbidden.test(js+html),`network/runtime dependency found: ${forbidden}`);
assert.match(data,/Nadia El Mansouri/);assert.match(data,/DONNÉES|directory/i);
assert.deepEqual(readdirSync(root).filter(x=>x==="node_modules"),[]);
console.log(`PASS ${files.length} required files, 6 views, local-only runtime and fixtures`);
